# ===================================================================
# Spring Boot Configuration for the local profile
# ===================================================================

# SERVER
server:
  error:
    include-exception: true # Include the "exception" attribute.
    include-stacktrace: always # When to include a "stacktrace" attribute.
    whitelabel.enabled: true

# LOGGING
logging:
  level:
    root: INFO
    com.emo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    reactor.netty.http.client: DEBUG

# SPRING
spring:
  jackson:
    serialization:
      indent_output: true
      write-null-map-values: true

# DATABASE
emo:
  master:
    datasource:
      url: jdbc:mysql://localhost:3306/emo?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root1234
      hikari:
        minimum-idle: 15
        maximum-pool-size: 25
        max-lifetime: 600000
        pool-name: hikaricp.hero.master
  jpa:
    properties:
      hibernate.hbm2ddl.auto: none
      hibernate.criteria.literal_handling_mode: bind
  maximum-jdbc-thread-pool-size: 25
